api: 3.0.0
api-version: 1.19
name: projectz
version: 1.2.1-SNAPSHOT
description: This is a simple Bukkit Plugin
author: ingeniom22

main: com.ingeniom22.Main

softdepend:
- Kingdoms

commands:
  Hello:
    description: Shows a hello message to the player
    usage: |
      /<command> shows a hello message to the player

