api: 3.0.0
api-version: 1.13
name: projectz
version: 1.0-SNAPSHOT
description: This is a simple Bukkit Plugin
author: ingeniom22

main: com.ingeniom22.Main

commands:
  Hello:
    description: Shows a hello message to the player
    usage: |
      /<command> shows a hello message to the player
